name: fixed
version: 2.4.1
homepage: https://github.com/onepub-dev/fixed
documentation: https://fixed.onepub.dev
description: Fixed scale decimal numbers with mathematical operations, formatting and parsing.
repository: https://github.com/onepub-dev/fixed
environment: 
  sdk: '>=2.19.0 <4.0.0'
dependencies: 
  decimal: ^2.3.0
  intl: ^0.18.0
  meta: ^1.9.0
dev_dependencies: 
  lint_hard: ^3.0.1
  test: ^1.16.0
