name: fixed
version: 2.0.0-beta.1
homepage: https://github.com/onepub-dev/fixed
description: Fixed scale decimal numbers with mathematical operations, formatting and parsing.
repository: https://github.com/onepub-dev/fixed
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  decimal: ^1.4.0
  intl: ^0.17.0
dev_dependencies: 
  lints: ^1.0.0
  test: ^1.16.0
