name: fixed
version: 1.0.0-beta3
homepage: https://github.com/bsutton/fixed
description: A starting point for Dart libraries or applications.
repository: https://github.com/bsutton/fixed
environment: 
  sdk: '>=2.14.4 <3.0.0'
dependencies: 
  decimal: ^1.4.0
  intl: ^0.17.0
dev_dependencies: 
  lints: ^1.0.0
  test: ^1.16.0
